### ISSUE TITLE
Some links not working in Module 1.3

### ISSUE THREAD

**Issue by aaryan2134** [microsoft/studentambassadors#62] opened 2022-12-16 13:22 UTC
## Describe the bug
Hyperlink texts are not pointing to the correct link currently on Module 1.3 in Get Started in C#
[Link](https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/3-learn-how-code-works.md#:~:text=How%20did%20your%20code%20work%3F)

## To Reproduce
1. Go to https://github.com/microsoft/studentambassadors/blob/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M01-write-your-first-c-sharp-code/includes/3-learn-how-code-works.md
2. Click on '[Store and retrieve data using literal and variable values in C#](https://github.com/MicrosoftDocs/learn-pr/blob/61e05994b92dde61c3ebd5d31d22a5dae000d246/learn/modules/csharp-literals-variables)' hyperlink text.
3. As we can see the link is broken currently
4. Same case is with - [Call methods from the .NET Class Library using C#](https://github.com/MicrosoftDocs/learn-pr/blob/61e05994b92dde61c3ebd5d31d22a5dae000d246/learn/modules/csharp-call-methods) hyperlink text on the same page

## Expected behavior
The links should point to the correct module
1. [Store and retrieve data using literal and variable values in C#](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/1_LP_AZ_get-started-with-c-sharp/M02-store-retrieve-values-using-variables-c-sharp)
2. [Call methods from the .NET Class Library using C#](https://github.com/microsoft/studentambassadors/tree/main/Bug-Bash/C%23%20Beginner%20Training/2_LP_AZ_create-run-simple-c-sharp-console-applications/M02-call-methods-from-net-class-library-using-c-sharp)

## Screenshots
![image](https://user-images.githubusercontent.com/22559451/208107119-d5ec5c88-fc92-4211-9a73-b2214e6c022d.png)

### Desktop (please complete the following information):
 - OS: [Windows]
 - Browser [Chrome]

***

#### 🎓 Add a tag to this issue for your current education role: **student**, **Student Ambassador** or **educator**.
**Student Ambassador**
***

**Comment by eric-camplin** [comment] 2023-01-11 02:31
@aaryan2134 Sorry - this is an internal link to an internal private repo topic that gets processed through the build system.

any link starting with 'https://github.com/MicrosoftDocs/learn-pr/blob' is OK and will resolve when published. this is dupe of https://github.com/microsoft/studentambassadors/issues/97

**Comment by alischumacher** [comment] 2023-02-28 04:40
Closing since this will be resolved when published

**Closed by alischumacher** 2023-02-28 04:40 UTC
Labels: C# Bug Bash
