### ISSUE TITLE
Knowledge Check files are not properly organized!

### ISSUE THREAD

**Issue by alshubati99** [microsoft/studentambassadors#101] opened 2022-12-25 13:50 UTC
## Describe the bug
The knowledge check files are not organized the way they are supposed to be. there must be a better way to organize those kinds of files in a way that it serves the objectives of the learning paths and modules. 

## To Reproduce
1. Go to 'learning modules'
2. Click on 'knowledge check'
3. got to 'edit file'
4. organize them differently, may be by adding the multiple choice answers as a list or what so ever. 

## Expected behavior
I expect that knowledge check files are organized in a better way.

### Desktop (please complete the following information):
 - OS: [Windows]
 - Browser [chrome]
 - Version [2.1]

## Additional context
I believe that if the lessons or modules files are organized properly, this gives the reader (student) a motive to complete the lesson.

***

####  **Student Ambassador**

***

**Comment by eric-camplin** [comment] 2023-01-10 21:55
@alshubati99 sorry about that. Our Markdown is hard to read for the knowledge checks and we should have supplied a warning about it. when transformed the knowledge checks look like this https://learn.microsoft.com/en-us/training/modules/csharp-basic-operations/7-knowledge-check

dupe of https://github.com/microsoft/studentambassadors/issues/113

**Comment by alischumacher** [comment] 2023-02-28 04:57
Closing issue since this will be resolved when transformed and published to Learn

**Closed by alischumacher** 2023-02-28 04:57 UTC
Labels: C# Bug Bash
